services:
  app:
    image: demo-springboot
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/springboot-learn
      SPRING_DATASOURCE_USERNAME: admin_support_sync_user
      SPRING_DATASOURCE_PASSWORD: akrem123
    networks:
      - s-network

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: springboot-learn
      POSTGRES_USER: admin_support_sync_user
      POSTGRES_PASSWORD: akrem123
    networks:
      - s-network

networks:
  s-network:
    driver: bridge