spring.application.name=demo3
server.port=8080

spring.datasource.url=jdbc:postgresql://postgres:5432/springboot-learn
spring.datasource.username=admin_support_sync_user
spring.datasource.password=akrem123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true